### ISSUE TITLE
Incorrect Parameter Settings in Example 3

### ISSUE THREAD

**Issue by huhanyu** [NREL/GEOPHIRES-X#168] opened 2024-03-28 01:51 UTC
In Example 3, there seems to be an issue with the parameter settings related to cracks，including Fracture Shape, Fracture Area, Number of Fractures, and Fracture Separation. As stated in the user manual, these parameters are not necessary and do not affect the simulation results. 

Since the "Number of Fractures" parameter does not affect the simulation results, should the "Reservoir Volume Option" only be set to 4 instead of defaulting to 3 as stated in the user manual? I am not sure if there are similar issues in Example 4, please confirm.
I have repeatedly adjusted their values and confirmed that they have no impact on the simulation. 

It would be helpful if this could be clarified in the documentation or if the unnecessary parameters could be removed from the example to avoid confusion.

![d1a3a8a04437d2d27b4e1e8b664a5e4](https://github.com/NREL/GEOPHIRES-X/assets/22694173/7ba397f0-57b3-4630-8447-e9c86c01f674)

![1e64b8fa567ffd08da65d032e368bb5](https://github.com/NREL/GEOPHIRES-X/assets/22694173/770644ed-bea3-448b-8a49-66cca9a9e365)
![8aa2da05faffb1d8308062256845e73](https://github.com/NREL/GEOPHIRES-X/assets/22694173/c625c839-8d2e-4a2c-9a00-362e47ef97e6)

![09c25ee4080d62f3f8e428522e220e4](https://github.com/NREL/GEOPHIRES-X/assets/22694173/04991f0c-46c3-41fb-b2a3-448e876743ef)

**Comment by softwareengineerprogrammer** [comment] 2024-03-29 00:19
@huhanyu Thanks for filing. I have assigned myself to look when time permits. In the meantime, if you are able to file a PR with a suggested fix, that will help us evaluate more efficiently and may expedite resolution.

**Comment by huhanyu** [comment] 2024-03-29 08:02
I've submitted a pr request to tweak example3 to make it conform to the user manual @softwareengineerprogrammer

**Comment by softwareengineerprogrammer** [comment] 2024-04-05 14:16
@huhanyu We discussed this in our sync and the outcome was we decided this is not a bug, marking as wontfix for now. (I will write up a more detailed explanation when time permits, but just wanted to give you the relevant update in the meantime.)

Thanks for submitting this issue - it is valuable feedback regardless of the outcome. Please don't hesitate to submit further issues and questions, we really appreciate them!

**Closed** 2024-04-25 19:25 UTC
Labels: wontfix
